# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: securitalConfigMap
#   namespace: prod
# data:
#   typeDNAKey: #{config.typeDNA.key}#
#   typeDNASecret: #{config.typeDNA.secret}#
#   twitterKey: #{config.twitter.key}#
#   twitterSecret: #{config.twitter.secret}#
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: securital
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securital
  template:
    metadata:
      labels:
        app: securital 
    spec:
      containers:
        - name: securital
          image: jodios/securital:latest #{deployment.image.name}#
          ports:
            - name: http-api
              containerPort: 80
              protocol: TCP
          # envFrom:
          #   - configMapRef:
          #       name: securitalConfigMap
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: securital
  namespace: prod
  labels:
    version: 0.1.203643-1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30425
  selector:
    app: securital